services:
  server:
    build: .
    container_name: bia
    ports:
      - 80:8080
  
    environment:
      DB_USER: postgres
      DB_PWD: postgres10
      DB_HOST: db-bia.c29gca8kizzb.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
    